name: Deploy Chrome Extension

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-extension:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Pack
        run: cd dist && zip -r ../chrome-extension-${{ github.ref_name }}.zip . && cd ..

      - name: Archive artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-${{ github.sha }}
          path: chrome-extension-${{ github.ref_name }}.zip

  deploy-extension:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build-extension
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: chrome-extension-${{ github.sha }}

      - name: Upload
        run: bunx chrome-webstore-upload-cli --source chrome-extension-${{ github.ref_name }}.zip
        env:
          EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
